# Copyright 2026 Imran Hafeez (RZA)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Deterministic plan replay from an evidence pack."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from pydantic import BaseModel

from replicant import __version__
from replicant.config.settings import Settings
from replicant.core.models import Catalog, RunRequest
from replicant.core.orchestrator import Orchestrator
from replicant.evidence.pack import plan_bytes


class ReplayResult(BaseModel):
    matches: bool
    parameters_match: bool
    technique_id: str
    expected_events: int
    observed_events: int
    expected_sha256: str
    observed_sha256: str
    warning: str | None = None


def replay_evidence(path: str | Path, catalog: Catalog, settings: Settings) -> ReplayResult:
    supplied = Path(path)
    replay_path = supplied / "replay.json" if supplied.is_dir() else supplied
    data = json.loads(replay_path.read_text(encoding="utf-8"))
    vendor = str(data["vendor"])
    replay_settings = settings.model_copy(update={"vendor": vendor})
    request = RunRequest(
        technique_id=str(data["technique_id"]),
        intensity=str(data["intensity"]),
        seed=int(data["seed"]),
        duration=data.get("duration"),
        no_send=True,
        controls=str(data["controls"]),
        anchor_epoch=int(data["anchor_epoch"]),
        param_overrides=dict(data.get("param_overrides") or {}),
        pace="burst",
    )
    plan = Orchestrator(catalog, replay_settings).build_plan(request)
    observed_hash = hashlib.sha256(plan_bytes(plan.events)).hexdigest()
    expected_hash = str(data["plan_sha256"])
    expected_count = int(data["event_count"])
    recorded_params = data.get("effective_params")
    parameters_match = recorded_params is None or plan.effective_params == dict(recorded_params)
    recorded_version = str(data["replicant_version"])
    warning = None
    if recorded_version != __version__:
        warning = (
            f"evidence was generated by Replicant {recorded_version}; replay used {__version__}"
        )
    return ReplayResult(
        matches=(
            observed_hash == expected_hash
            and len(plan.events) == expected_count
            and parameters_match
        ),
        parameters_match=parameters_match,
        technique_id=request.technique_id,
        expected_events=expected_count,
        observed_events=len(plan.events),
        expected_sha256=expected_hash,
        observed_sha256=observed_hash,
        warning=warning,
    )
